### ISSUE TITLE
📌 Fix: Yardım İstiyorum Event

### ISSUE THREAD

**Issue by TarikKaanKoc** [VB10/sesimiduy#87]
### 🛠 Tasks:

- [x] Yardım istiyorum sayfasında **"Neye İhtiyacınız Var?"** dropdown menüsünde item'lar arasında yer almayan taleplerde girilebilmelidir. (Örneğin: Aşağıdaki görselde, çeşitli ihtiyaç talepleri girilmiştir fakat listede olmayan malzemelerde girilebilmeli. Örneğin: **"Erzak"** İtem'lar arasında yer almasada yeni bir item olarak girilebilmeli.)

<img width="1792" alt="Ekran Resmi 2023-02-14 18 47 37" src="https://user-images.githubusercontent.com/83168207/218864972-c26b9235-09c6-41ea-8070-d1d26b272fe7.png">

---

- [ ] Aşağıdaki, UI'da güncel yardım istiyorum sayfası görülmektedir. Şekilde görüldüğü gibi güncellenmeli ve il, ilçe, mah, sk olarak 81 ilimiz  olmalı. 
- [ ] Aşağıdaki UI'da telefon numarası hidden text uyuşmazlığı giderilmeli. (Unutulmamalı.) Şekilde: +90 (xxx) xx xx olarak görülmektedir. Bu şekilde düzeltebilirsiniz: **0 (5XX) XXX-XX-XX**
- [ ] **1.) Checkbox:** Aydınlatma metni henüz hazır değil fakat şimdilik checkbox'ı ekleyebilirsiniz. Av ile görüşüldü, açık rıza ve aydınlatma metni de veri işlemeye ilişkin metin eklenerek sorun oluşturmaz diye görüş bildirdiler. Proje somutlaştığında bir metin hazırlanacaktır.
- [ ] **2.) Checkbox:** 2. Checkbox için aşağıdaki metni eklleyebilrisiniz: 

```text
Enkaz, yıkım, yardım ve destek ihtiyaçları konusunda verdiğim bilgilerin doğru ve teyit edilmiş olduğunu, bilgi kirliliği ve yanlış uygulamalara yol açmamak için gerekli tüm önlem ve tedbirleri aldığımı, vermiş olduğum bilgilerde meydana gelen değişiklik ve güncellemeleri bildireceğimi kabul ve beyan ederim. 
```

<img width="894" alt="Ekran Resmi 2023-02-14 19 06 53" src="https://user-images.githubusercontent.com/83168207/218866891-5835a5cd-a0b9-4f22-b1bb-1061350b35ea.png">
 
- [ ] Aşağıdaki UI'da görüldüğü üzere, seçilen ihtiyaç malzemesinin kullanıcı tarafınca adet bilgisi girilebiliyor olmalı. 

<img width="807" alt="Ekran Resmi 2023-02-15 00 30 07" src="https://user-images.githubusercontent.com/83168207/218867731-04ca4fdf-dbaa-4811-88c9-3c591ba52cdc.png">

---

**Comment by VB10** [comment]
@TarikKaanKoc Aşağıdaki UI'da telefon numarası hidden text uyuşmazlığı giderilmeli. (Unutulmamalı.) Şekilde: +90 (xxx) xx xx olarak görülmektedir. Bu şekilde düzeltebilirsiniz: 0 (5XX) XXX-XX-XX +90 nerede gozukuyor resım paylasabılır mısın

**Comment by VB10** [comment]
@TarikKaanKoc şehir sokak bilgisi bu şekilde yapılmaz bunun google maps api ile bağlnıp adamın girmesi ve pinlemesi gerekir elimzide il ilçe var ama sokaklar ciddi fakrlı veriler veya cadde bunlar şuan yok diyeiblirm teyit etmek lazım

**Comment by VB10** [comment]
@TarikKaanKoc  Aşağıdaki UI'da görüldüğü üzere, seçilen ihtiyaç malzemesinin kullanıcı tarafınca adet bilgisi girilebiliyor olmalı.
 bu tasarım sadece webde calısabilecek bir iş mobilde bunu yapınca adamın fonksiyonetilsi çok düşecek ondan bu sayfa popupdan ziyade sayfa olarak açılacak bundan sonra yoksa çok zor girilir bu alanlar

**Comment by MehmetKaranlik** [comment]
olmayan itemları ekleyebilme özelliği eklendi @TarikKaanKoc 

https://user-images.githubusercontent.com/89414084/219254866-7cf4d69f-9157-4502-9421-0b0b8a3f7146.mov

**Comment by TarikKaanKoc** [comment]
> olmayan itemları ekleyebilme özelliği eklendi @TarikKaanKoc

Çok güzel emeğinize sağlık 🙏🏻

**Comment by VB10** [comment]
eline saglik
